Repository AY2324S1-CS2103T-F10-2/tp, pull requests merged in 2023-11, with the labels that each got.

#133 Fix Bugs
  docs/diagrams/Date.puml
  src/main/java/seedu/lovebook/MainApp.java
  src/main/java/seedu/lovebook/logic/commands/ListPrefsCommand.java
  src/main/java/seedu/lovebook/model/DatePrefs.java
  src/main/java/seedu/lovebook/model/ModelManager.java
  src/main/java/seedu/lovebook/model/ReadOnlyDatePrefs.java
  src/main/java/seedu/lovebook/model/date/Age.java
  src/main/java/seedu/lovebook/model/date/Date.java
  src/main/java/seedu/lovebook/storage/JsonSerializableDatePrefs.java
  src/test/java/seedu/lovebook/model/date/AgeTest.java
Labels: priority.High

#134 Improve Presets Bar
  docs/DeveloperGuide.md
  docs/Style.puml
  docs/UGDraft.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/Date.puml
  docs/diagrams/Filter Activity.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SortActivity.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/team/bobscodedump.md
  docs/team/cleon2.md
  docs/team/lynnlow175.md
  docs/team/ryamgoh.md
  docs/team/shishirbychapur.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/lovebook/MainApp.java
  src/main/java/seedu/lovebook/model/LoveBook.java
  src/main/java/seedu/lovebook/model/date/UniqueDateList.java
  src/main/java/seedu/lovebook/storage/JsonDatePrefsStorage.java
  src/main/java/seedu/lovebook/ui/DateListPanel.java
  src/main/java/seedu/lovebook/ui/MainWindow.java
  src/main/java/seedu/lovebook/ui/PresetsBar.java
  src/main/resources/view/DateListCard.fxml
  src/main/resources/view/DateListPanel.fxml
  src/main/resources/view/PresetsBar.fxml
  src/test/java/seedu/lovebook/model/date/UniqueDateListTest.java
Labels: enhancement

#136 Edit User Guide, Developer Guide and Command names
  docs/DeveloperGuide.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/lovebook/MainApp.java
  src/main/java/seedu/lovebook/logic/Logic.java
  src/main/java/seedu/lovebook/logic/commands/AddCommand.java
  src/main/java/seedu/lovebook/logic/commands/BestMatchCommand.java
  src/main/java/seedu/lovebook/logic/commands/BlindDateCommand.java
  src/main/java/seedu/lovebook/logic/commands/ClearCommand.java
  src/main/java/seedu/lovebook/logic/commands/DeleteCommand.java
  src/main/java/seedu/lovebook/logic/commands/EditCommand.java
  src/main/java/seedu/lovebook/logic/commands/ExitCommand.java
  src/main/java/seedu/lovebook/logic/commands/FilterCommand.java
  src/main/java/seedu/lovebook/logic/commands/FindCommand.java
  src/main/java/seedu/lovebook/logic/commands/ListCommand.java
  src/main/java/seedu/lovebook/logic/commands/SetPrefCommand.java
  src/main/java/seedu/lovebook/logic/commands/ShowPrefCommand.java
  src/main/java/seedu/lovebook/logic/commands/SortCommand.java
  src/main/java/seedu/lovebook/logic/commands/StarCommand.java
  src/main/java/seedu/lovebook/logic/commands/UnstarCommand.java
  src/main/java/seedu/lovebook/logic/parser/LoveBookParser.java
  src/main/java/seedu/lovebook/model/LoveBook.java
  src/main/java/seedu/lovebook/model/Model.java
  src/main/java/seedu/lovebook/model/ModelManager.java
  src/main/java/seedu/lovebook/model/date/horoscope/Horoscope.java
  src/main/java/seedu/lovebook/storage/JsonSerializableLoveBook.java
  src/test/java/seedu/lovebook/logic/commands/BlindDateCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/lovebook/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/EditCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/ShowPrefCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/StarCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/UnstarCommandTest.java
Labels: documentation

#150 fix ui of pref bar
  src/main/resources/view/DarkTheme.css
Labels: enhancement

#154 Update UG
  docs/UserGuide.md
Labels: documentation

#223 Fix Avatar Missing Bug + Improve UG
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  src/main/java/seedu/lovebook/model/date/Avatar.java
Labels: enhancement

#224 Improve UG + Conduct Testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  docs/site.json
  docs/team/shishirbychapur.md
  src/main/java/seedu/lovebook/model/date/Avatar.java
  src/test/java/seedu/lovebook/model/date/AgeTest.java
  src/test/java/seedu/lovebook/model/date/AvatarTest.java
  src/test/java/seedu/lovebook/model/date/DateTest.java
  src/test/java/seedu/lovebook/model/date/GenderTest.java
  src/test/java/seedu/lovebook/model/date/UniqueDateListTest.java
Labels: documentation, testing

#227 Add Tests for Sample Dates/Date Prefs + Fix Bugs
  docs/team/bobscodedump.md
  docs/team/cleon2.md
  docs/team/lynnlow175.md
  docs/team/ryamgoh.md
  docs/team/shishirbychapur.md
  src/main/java/seedu/lovebook/logic/Messages.java
  src/main/java/seedu/lovebook/model/DatePrefs.java
  src/main/java/seedu/lovebook/model/date/Date.java
  src/main/java/seedu/lovebook/ui/DateCard.java
  src/main/resources/view/DateListCard.fxml
  src/test/java/seedu/lovebook/model/util/SampleDataUtilTest.java
  src/test/java/seedu/lovebook/model/util/SampleDatePrefUtilTest.java
Labels: enhancement, testing

#233 Update User Guide and Fix SetP
  docs/UserGuide.md
  docs/images/user-commands/addCommandExample.png
  docs/images/user-commands/bestMatchCommandExample1.png
  docs/images/user-commands/bestMatchCommandExample2.png
  docs/images/user-commands/blindDateCommandExample1.png
  docs/images/user-commands/blindDateCommandExample2.png
  docs/images/user-commands/clearCommandExample1.png
  docs/images/user-commands/clearCommandExample2.png
  docs/images/user-commands/deleteCommandExample.png
  docs/images/user-commands/editCommandExample.png
  docs/images/user-commands/helpCommandExample.png
  docs/images/user-commands/listCommandExample.png
  docs/images/user-commands/setPCommandExample.png
  src/main/java/seedu/lovebook/logic/commands/SetPrefCommand.java
Labels: documentation, type.Bug

#238 Add UI Tests
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/seedu/lovebook/ui/DateCard.java
  src/test/data/JsonSerializableLoveBookTest/typicalDatesLoveBook.json
  src/test/java/seedu/lovebook/logic/LogicManagerTest.java
  src/test/java/seedu/lovebook/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/lovebook/logic/commands/AddCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/ClearCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/EditCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/FilterCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/FindCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/ListCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/SortCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/StarCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/UnstarCommandTest.java
  src/test/java/seedu/lovebook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/lovebook/model/LoveBookTest.java
  src/test/java/seedu/lovebook/model/ModelManagerTest.java
  src/test/java/seedu/lovebook/model/date/DateTest.java
  src/test/java/seedu/lovebook/model/date/RandomPredicateTest.java
  src/test/java/seedu/lovebook/model/date/UniqueDateListTest.java
  src/test/java/seedu/lovebook/storage/JsonAdaptedDatePrefsTest.java
  src/test/java/seedu/lovebook/storage/JsonAdaptedDateTest.java
  src/test/java/seedu/lovebook/storage/JsonLoveBookStorageTest.java
  src/test/java/seedu/lovebook/storage/JsonSerializableLoveBookTest.java
  src/test/java/seedu/lovebook/storage/StorageManagerTest.java
  src/test/java/seedu/lovebook/testutil/TypicalDates.java
  src/test/java/seedu/lovebook/ui/DateCardTest.java
Labels: testing

#247 added test for show preferences
  src/test/java/seedu/lovebook/logic/commands/ShowPrefCommandTest.java
Labels: testing

#248 Add Preset Bar Tests
  src/main/java/seedu/lovebook/ui/CommandBox.java
  src/main/java/seedu/lovebook/ui/PresetsBar.java
  src/main/java/seedu/lovebook/ui/ResultDisplay.java
  src/main/resources/view/PresetsBar.fxml
  src/test/java/seedu/lovebook/ui/PresetsBarTest.java
  src/test/java/seedu/lovebook/ui/StubCommandExecutor.java
Labels: testing

#252 Organize UG
  docs/UserGuide.md
  src/test/java/seedu/lovebook/ui/PresetsBarTest.java
Labels: documentation

#253 Improve UG + Fix UI Bug
  docs/UserGuide.md
  docs/images/navigation.png
  src/main/resources/view/DateListCard.fxml
Labels: documentation, enhancement

#254 Fix Images
  docs/UserGuide.md
Labels: documentation

#256 Improve UG + Update PPP
  docs/AboutUs.md
  docs/DevOps.md
  docs/Documentation.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/index.md
  docs/team/shishirbychapur.md
Labels: documentation

#258 Change PPP
  docs/team/shishirbychapur.md
Labels: documentation

#265 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#267 Update UG
  docs/UserGuide.md
Labels: documentation

#271 Branch update ug
  docs/UserGuide.md
Labels: documentation

#272 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequence.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/DateClassDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SortSequence.puml
  src/main/java/seedu/lovebook/logic/commands/AddCommand.java
  src/main/java/seedu/lovebook/logic/commands/ListCommand.java
  src/main/java/seedu/lovebook/logic/commands/SortCommand.java
  src/main/java/seedu/lovebook/model/Model.java
  src/main/java/seedu/lovebook/model/ModelManager.java
  src/test/java/seedu/lovebook/logic/commands/AddCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/SetPrefCommandTest.java
Labels: documentation

#276 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StarActivity.puml
  docs/diagrams/UnstarActivity.puml
Labels: documentation

#290 Fix UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation
