Repository AY2324S1-CS2103T-F10-2/tp, pull requests merged in 2023-10, with the labels that each got.

#41 Rename to ryamgoh.png and PPP Skeleton
  docs/AboutUs.md
  docs/images/ryamgoh.png
  docs/team/ryamgoh.md
Labels: enhancement

#44 Change Figma in UserGuide images
  docs/UserGuide.md
  docs/images/user-guide/Figma.png
Labels: documentation

#49 Update README.md
  README.md
  docs/images/Ui.png
Labels: documentation

#50 Add Target User Profile
  docs/DeveloperGuide.md
Labels: documentation

#53 Update README.md
  README.md
Labels: documentation

#54 Update README.md
  README.md
Labels: documentation

#58 Update DG to reflect NFRs and Remove NFR from UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#60 Add Info to ryamgoh.md
  docs/team/ryamgoh.md
Labels: documentation

#63 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#64 Update Target User Profile
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
Labels: documentation

#65 Update lynnlow175.md
  docs/team/lynnlow175.md
Labels: documentation

#85 Feature/welcome message
  src/main/java/seedu/lovebook/MainApp.java
  src/main/java/seedu/lovebook/logic/Logic.java
  src/main/java/seedu/lovebook/logic/LogicManager.java
  src/main/java/seedu/lovebook/logic/Messages.java
  src/main/java/seedu/lovebook/model/Model.java
  src/main/java/seedu/lovebook/model/ModelManager.java
  src/main/java/seedu/lovebook/ui/MainWindow.java
  src/main/java/seedu/lovebook/ui/ResultDisplay.java
  src/test/java/seedu/lovebook/logic/LogicManagerTest.java
  src/test/java/seedu/lovebook/logic/commands/AddCommandTest.java
  src/test/java/seedu/lovebook/model/ModelManagerTest.java
Labels: enhancement

#89 Add Preferences
  src/main/java/seedu/lovebook/MainApp.java
  src/main/java/seedu/lovebook/model/DatePrefs.java
  src/main/java/seedu/lovebook/model/LoveBook.java
  src/main/java/seedu/lovebook/model/Model.java
  src/main/java/seedu/lovebook/model/ModelManager.java
  src/main/java/seedu/lovebook/model/ReadOnlyDatePrefs.java
  src/main/java/seedu/lovebook/model/ReadOnlyLoveBook.java
  src/main/java/seedu/lovebook/model/UserPrefs.java
  src/main/java/seedu/lovebook/model/person/User.java
  src/main/java/seedu/lovebook/model/util/SampleDatePrefUtil.java
  src/main/java/seedu/lovebook/storage/DatePrefsStorage.java
  src/main/java/seedu/lovebook/storage/JsonAdaptedDate.java
  src/main/java/seedu/lovebook/storage/JsonAdaptedDatePrefs.java
  src/main/java/seedu/lovebook/storage/JsonLoveBookDatePrefs.java
  src/main/java/seedu/lovebook/storage/JsonSerializableDatePrefs.java
  src/main/java/seedu/lovebook/storage/JsonSerializableLoveBook.java
  src/main/java/seedu/lovebook/storage/Storage.java
  src/main/java/seedu/lovebook/storage/StorageManager.java
  src/test/java/seedu/lovebook/logic/LogicManagerTest.java
  src/test/java/seedu/lovebook/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/lovebook/logic/commands/AddCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/ClearCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/EditCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/FindCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/ListCommandTest.java
  src/test/java/seedu/lovebook/model/ModelManagerTest.java
  src/test/java/seedu/lovebook/storage/JsonAdaptedDateTest.java
  src/test/java/seedu/lovebook/storage/JsonDatePrefsStorageTest.java
  src/test/java/seedu/lovebook/testutil/TypicalDatePrefs.java
Labels: enhancement

#92 Settle merge conflict
  src/main/java/seedu/lovebook/logic/Messages.java
  src/main/java/seedu/lovebook/logic/commands/AddCommand.java
  src/main/java/seedu/lovebook/logic/commands/EditCommand.java
  src/main/java/seedu/lovebook/logic/parser/AddCommandParser.java
  src/main/java/seedu/lovebook/logic/parser/CliSyntax.java
  src/main/java/seedu/lovebook/logic/parser/EditCommandParser.java
  src/main/java/seedu/lovebook/logic/parser/ParserUtil.java
  src/main/java/seedu/lovebook/model/person/Date.java
  src/main/java/seedu/lovebook/model/tag/Tag.java
  src/main/java/seedu/lovebook/model/util/SampleDataUtil.java
  src/main/java/seedu/lovebook/storage/JsonAdaptedDate.java
  src/main/java/seedu/lovebook/storage/JsonAdaptedTag.java
  src/main/java/seedu/lovebook/ui/PersonCard.java
  src/test/java/seedu/lovebook/logic/LogicManagerTest.java
  src/test/java/seedu/lovebook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/lovebook/logic/commands/EditCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/EditDateDescriptorTest.java
  src/test/java/seedu/lovebook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/lovebook/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/lovebook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/lovebook/model/LoveBookTest.java
  src/test/java/seedu/lovebook/model/person/DateTest.java
  src/test/java/seedu/lovebook/model/person/UniqueDateListTest.java
  src/test/java/seedu/lovebook/model/tag/TagTest.java
  src/test/java/seedu/lovebook/storage/JsonAdaptedDateTest.java
  src/test/java/seedu/lovebook/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/lovebook/testutil/PersonBuilder.java
  src/test/java/seedu/lovebook/testutil/PersonUtil.java
  src/test/java/seedu/lovebook/testutil/TypicalPersons.java
Labels: severity.High

#94 Feature edit preferences
  src/main/java/seedu/lovebook/logic/Messages.java
  src/main/java/seedu/lovebook/logic/commands/AddCommand.java
  src/main/java/seedu/lovebook/logic/commands/EditCommand.java
  src/main/java/seedu/lovebook/logic/commands/SetPrefCommand.java
  src/main/java/seedu/lovebook/logic/parser/LoveBookParser.java
  src/main/java/seedu/lovebook/logic/parser/SetPrefCommandParser.java
  src/main/java/seedu/lovebook/model/DatePrefs.java
  src/main/java/seedu/lovebook/model/person/horoscope/Horoscope.java
  src/main/java/seedu/lovebook/model/util/SampleDatePrefUtil.java
  src/main/java/seedu/lovebook/storage/JsonAdaptedDatePrefs.java
Labels: enhancement

#95 Refactor/filter
  src/main/java/seedu/lovebook/commons/util/PredicatesUtil.java
  src/main/java/seedu/lovebook/logic/commands/FilterCommand.java
  src/main/java/seedu/lovebook/logic/parser/FilterCommandParser.java
  src/main/java/seedu/lovebook/model/person/MetricContainsKeywordPredicate.java
  src/test/java/seedu/lovebook/logic/commands/FilterCommandTest.java
  src/test/java/seedu/lovebook/logic/parser/FilterCommandParserTest.java
Labels: type.Enhancement

#96 Improve GUI
  bin/main/view/MainWindow.fxml
  src/main/java/seedu/lovebook/ui/UiManager.java
  src/main/resources/images/bot.png
  src/main/resources/images/pink-gradient.jpg
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/lovebook/commons/util/AppUtilTest.java
Labels: enhancement

#97 Feature/random date
  src/main/java/seedu/lovebook/logic/Messages.java
  src/main/java/seedu/lovebook/logic/commands/RandomCommand.java
  src/main/java/seedu/lovebook/logic/parser/LoveBookParser.java
  src/main/java/seedu/lovebook/model/Model.java
  src/main/java/seedu/lovebook/model/ModelManager.java
  src/main/java/seedu/lovebook/model/person/RandomPredicate.java
  src/test/java/seedu/lovebook/logic/commands/AddCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/RandomCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/SetPrefCommandTest.java
  src/test/java/seedu/lovebook/model/ModelManagerTest.java
  src/test/java/seedu/lovebook/model/person/RandomPredicateTest.java
Labels: enhancement

#105 Add Validation for Height for 1 to 250
  src/main/java/seedu/lovebook/logic/commands/AddCommand.java
  src/main/java/seedu/lovebook/model/person/Height.java
  src/test/data/JsonLoveBookStorageTest/invalidAndValidDateLoveBook.json
  src/test/data/JsonSerializableLoveBookTest/invalidDateLoveBook.json
  src/test/data/JsonSerializableLoveBookTest/typicalDatesLoveBook.json
  src/test/java/seedu/lovebook/logic/commands/FilterCommandTest.java
  src/test/java/seedu/lovebook/model/person/MetricContainsKeywordPredicateTest.java
  src/test/java/seedu/lovebook/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/lovebook/storage/JsonSerializableLoveBookTest.java
  src/test/java/seedu/lovebook/testutil/TypicalPersons.java
Labels: enhancement

#106 Add feature-Presets for the command box
  src/main/java/seedu/lovebook/ui/CommandBox.java
  src/main/java/seedu/lovebook/ui/HelpWindow.java
  src/main/java/seedu/lovebook/ui/MainWindow.java
  src/main/java/seedu/lovebook/ui/PresetsBar.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PresetsBar.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: enhancement

#108 Add Random Avatar Feature + Update UG + Fix Minor Bug
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/user-guide/Figma.png
  docs/tutorials/AddRemark.md
  src/main/java/seedu/lovebook/logic/commands/EditCommand.java
  src/main/java/seedu/lovebook/ui/DateCard.java
  src/main/java/seedu/lovebook/ui/PersonListPanel.java
  src/main/resources/images/avatars/female-avatar.png
  src/main/resources/images/avatars/female/1.png
  src/main/resources/images/avatars/female/2.png
  src/main/resources/images/avatars/female/3.png
  src/main/resources/images/avatars/female/4.png
  src/main/resources/images/avatars/female/5.png
  src/main/resources/images/avatars/female/6.png
  src/main/resources/images/avatars/female/7.png
  src/main/resources/images/avatars/female/8.png
  src/main/resources/images/avatars/female/9.png
  src/main/resources/images/avatars/male/1.png
  src/main/resources/images/avatars/male/2.png
  src/main/resources/images/avatars/male/3.png
  src/main/resources/images/avatars/male/4.png
  src/main/resources/images/avatars/male/5.png
  src/main/resources/images/avatars/male/6.png
  src/main/resources/images/avatars/male/7.png
  src/main/resources/images/avatars/male/8.png
  src/main/resources/images/avatars/male/9.png
Labels: documentation, enhancement

#131 first iteration of algorithm
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/seedu/lovebook/logic/commands/BestMatchCommand.java
  src/main/java/seedu/lovebook/logic/parser/LoveBookParser.java
  src/main/java/seedu/lovebook/model/Model.java
  src/main/java/seedu/lovebook/model/ModelManager.java
  src/main/java/seedu/lovebook/model/date/Date.java
  src/test/java/seedu/lovebook/logic/commands/AddCommandTest.java
  src/test/java/seedu/lovebook/logic/commands/SetPrefCommandTest.java
Labels: enhancement, priority.High
